spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gb-db
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/master.xml
  thymeleaf:
    encoding: UTF-8
